export enum MessageTypes {
	INIT_GAME = "INIT_GAME",
	MATRIX = "MATRIX",
	MARK = "MARK",
}

export enum GAME_STATUS {
	WAITING_FOR_PLAYER = "WAITING_FOR_PLAYER",
	GAME_STARTED = "GAME_STARTED",
	WINNER = "WINNER",
	LOOSER = "LOOSER",
	DRAW = "DRAW",
	LEAVE = "LEAVE",
	TERMINATED = "TERMINATED",
}

